# Generated by Django 5.2.6 on 2025-09-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_populate_tenant_slugs'),
    ]

    operations = [
    ]
