# Generated by Django 5.2.6 on 2025-09-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_populate_tenant_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
